apiVersion: v1
kind: ConfigMap
metadata:
  name: maxicloud-manager-config
data:
  HEALTH_PROBE_BIND_ADDRESS: ":8081"
  GHCR_HOST: "ghcr.io/saitamau-maximum"
  INGRESS_CLASS: "nginx"
  BASE_DOMAIN: "maxicloud.maximum.vc"
