apiVersion: v1
kind: Secret
metadata:
  name: maxicloud-manager-secret
type: Opaque
stringData:
  GHCR_TOKEN: "REPLACE_ME"
  private-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_ME
    -----END RSA PRIVATE KEY-----
