apiVersion: maxicloud.maximum.vc/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: maxicloud
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  image: ghcr.io/saitamau-maximum/maxicloud:latest
  replicas: 1
  expose:
    port: 3000
