apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: maxicloud-manager-config
    envs:
      - config.env
  - name: maxicloud-gateway-config
    envs:
      - config.env

secretGenerator:
  - name: maxicloud-manager-secret
    envs:
      - secret.env
    files:
      - private-key.pem=private-key.pem
  - name: maxicloud-gateway-secret
    envs:
      - secret.env
