name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Backend lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check linter configuration
        run: make lint-config
      - name: Run linter
        run: make lint

  frontend-lint:
    name: Frontend lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: dashboard/.node-version
          cache: pnpm
          cache-dependency-path: dashboard/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run frontend check
        run: pnpm run check
